"""Application assembly, lifecycle and bounded pipeline orchestration.

Domain packages never depend on this composition root.
"""

from .adapters import (
    AccountPolicy,
    AsyncExecutionPortBridge,
    CanonicalOmsApplicationService,
    ExecutionBridgeError,
    ExecutionBridgeStateError,
    FeatureEngineAdapter,
    MarketStateGateAdapter,
    MarketStateUpdater,
    OmsIdentityPolicy,
    OmsInvariantError,
    OmsPersistenceError,
    OmsRecoveryError,
    OrderParameters,
    OrderPolicy,
)
from .application import TradingApplication
from .pipeline import (
    ExecutionPort,
    FeaturePort,
    HealthPort,
    MarketStatePort,
    OmsPort,
    PipelineFailure,
    PipelineInvariantError,
    PipelineOutcome,
    PipelineRecorderPort,
    PipelineResult,
    PipelineStage,
    PipelineStateError,
    PipelineStatus,
    PortfolioReadPort,
    RiskPort,
    StageOutcome,
    StageTrace,
    StateGate,
    StrategyPort,
    TradingPipeline,
    ValidationPort,
)
from .recorder_handoff import (
    OverflowPolicy,
    RecorderHandoff,
    RecorderHandoffError,
    RecorderHandoffOverflowError,
    RecorderHandoffSnapshot,
    RecorderHandoffStateError,
    RecorderHandoffStatus,
    RecorderWorkerFailedError,
)

__all__ = [
    "AccountPolicy",
    "AsyncExecutionPortBridge",
    "CanonicalOmsApplicationService",
    "ExecutionBridgeError",
    "ExecutionBridgeStateError",
    "ExecutionPort",
    "FeatureEngineAdapter",
    "FeaturePort",
    "HealthPort",
    "MarketStateGateAdapter",
    "MarketStatePort",
    "MarketStateUpdater",
    "OmsIdentityPolicy",
    "OmsInvariantError",
    "OmsPersistenceError",
    "OmsPort",
    "OmsRecoveryError",
    "OrderParameters",
    "OrderPolicy",
    "OverflowPolicy",
    "PipelineFailure",
    "PipelineInvariantError",
    "PipelineOutcome",
    "PipelineRecorderPort",
    "PipelineResult",
    "PipelineStage",
    "PipelineStateError",
    "PipelineStatus",
    "PortfolioReadPort",
    "RecorderHandoff",
    "RecorderHandoffError",
    "RecorderHandoffOverflowError",
    "RecorderHandoffSnapshot",
    "RecorderHandoffStateError",
    "RecorderHandoffStatus",
    "RecorderWorkerFailedError",
    "RiskPort",
    "StageOutcome",
    "StageTrace",
    "StateGate",
    "StrategyPort",
    "TradingApplication",
    "TradingPipeline",
    "ValidationPort",
]
